# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
       
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
         
      # install openmpi
      - name: install ubuntu mpi
        run: sudo apt-get install openmpi-bin openmpi-common openmpi-doc libopenmpi2 libopenmpi-dev
        
      # Runs a configure
      - name: configure
        run: mkdir build && cd build && cmake ../Nwpw

      # Compiling the code
      - name: builder
        run: cmake --build build && ls

      # Runs a set of commands using the runners shell
      - name: Run the DEMOs -  multi-line script
        run: |
          echo Add other actions to build,
          echo Running DEMO2/ericmd00.nw 
          cd DEMO2 && cat ericmd00.nw && ../build/pwdft ericmd00.nw
          echo Running CuNanoDEMO/cunano00.nw 
          cd ../CuNanoDEMO && cat cunano00.nw && ../build/pwdft cunano00.nw
